# Copyright (C) 2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
    ".gitignore",
    ".github/linters/.pylintrc",
    ".github/linters/.flake8",
    "robotics-project.json",
]
SPDX-FileCopyrightText = "2026 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
