# Copyright (C) 2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

include_guard(GLOBAL)

function(configure_ros_debian_package)
  if(NOT DEFINED ROS_DISTRO OR ROS_DISTRO STREQUAL "")
    return()
  endif()

  set(control_file "${CMAKE_CURRENT_SOURCE_DIR}/${ROS_DISTRO}/debian/control")
  set(changelog_file "${CMAKE_CURRENT_SOURCE_DIR}/${ROS_DISTRO}/debian/changelog")
  foreach(metadata_file IN ITEMS "${control_file}" "${changelog_file}")
    if(NOT EXISTS "${metadata_file}")
      message(FATAL_ERROR "Debian package metadata not found: ${metadata_file}")
    endif()
  endforeach()

  file(READ "${control_file}" control_contents)
  file(READ "${changelog_file}" changelog_contents)
  string(REGEX MATCH "Package:[ \t]*([^\r\n]+)" package_match "${control_contents}")
  set(package_name "${CMAKE_MATCH_1}")
  file(STRINGS "${control_file}" control_lines)
  set(current_control_field "")
  set(package_dependencies "")
  set(package_recommends "")
  foreach(control_line IN LISTS control_lines)
    if(control_line MATCHES "^([A-Za-z][A-Za-z-]*):[ \t]*(.*)$")
      set(current_control_field "${CMAKE_MATCH_1}")
      set(current_control_value "${CMAKE_MATCH_2}")
      if(current_control_field STREQUAL "Depends")
        set(package_dependencies "${current_control_value}")
      elseif(current_control_field STREQUAL "Recommends")
        set(package_recommends "${current_control_value}")
      endif()
    elseif(control_line MATCHES "^[ \t]+(.*)$")
      if(current_control_field STREQUAL "Depends")
        string(APPEND package_dependencies " ${CMAKE_MATCH_1}")
      elseif(current_control_field STREQUAL "Recommends")
        string(APPEND package_recommends " ${CMAKE_MATCH_1}")
      endif()
    else()
      set(current_control_field "")
    endif()
  endforeach()
  string(REGEX REPLACE "\\$\\{[^}]+\\},?[ \t]*" "" package_dependencies "${package_dependencies}")
  string(REGEX REPLACE "\\$\\{[^}]+\\},?[ \t]*" "" package_recommends "${package_recommends}")
  string(REGEX REPLACE "[ \t\r\n]+" " " package_dependencies "${package_dependencies}")
  string(REGEX REPLACE "[ \t\r\n]+" " " package_recommends "${package_recommends}")
  string(REPLACE ";" ", " package_dependencies "${package_dependencies}")
  string(REPLACE ";" ", " package_recommends "${package_recommends}")
  string(REGEX REPLACE ",[ \t]*$" "" package_dependencies "${package_dependencies}")
  string(REGEX REPLACE ",[ \t]*$" "" package_recommends "${package_recommends}")
  string(REGEX MATCH "^[^(]+\\(([^)]+)\\)" changelog_match "${changelog_contents}")
  set(package_version "${CMAKE_MATCH_1}${ADBSCAN_PACKAGE_VERSION_SUFFIX}")
  if(package_name STREQUAL "" OR package_version STREQUAL "")
    message(FATAL_ERROR "Package metadata could not be read from ${control_file} or ${changelog_file}")
  endif()

  install(FILES "${changelog_file}"
    DESTINATION "share/doc/${package_name}"
    RENAME "changelog.Debian"
  )

  set(CPACK_GENERATOR "DEB")
  set(CPACK_PACKAGE_NAME "${package_name}")
  set(CPACK_PACKAGE_VERSION "${package_version}")
  set(CPACK_PACKAGE_CONTACT "ECI Maintainer <eci-maintainer@intel.com>")
  set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${PROJECT_NAME}")
  set(CPACK_PACKAGING_INSTALL_PREFIX "/opt/ros/${ROS_DISTRO}")
  set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
  set(CPACK_DEBIAN_PACKAGE_DEPENDS "${package_dependencies}")
  set(CPACK_DEBIAN_PACKAGE_RECOMMENDS "${package_recommends}")
  set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

  include(CPack)
endfunction()

function(configure_ros_debian_package_with_metadata)
  set(options)
  set(one_value_args PACKAGE_NAME DESCRIPTION CONTACT)
  set(multi_value_args BUILD_DEPENDS DEPENDS RECOMMENDS)
  cmake_parse_arguments(ROS_DEBIAN "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

  if(NOT DEFINED ROS_DISTRO OR ROS_DISTRO STREQUAL "")
    return()
  endif()
  if(ROS_DEBIAN_PACKAGE_NAME STREQUAL "")
    message(FATAL_ERROR "PACKAGE_NAME is required")
  endif()

  set(changelog_file "${CMAKE_CURRENT_SOURCE_DIR}/${ROS_DISTRO}/debian/changelog")
  if(NOT EXISTS "${changelog_file}")
    message(FATAL_ERROR "Debian changelog not found: ${changelog_file}")
  endif()
  file(READ "${changelog_file}" changelog_contents)
  string(REGEX MATCH "^[^(]+\\(([^)]+)\\)" changelog_match "${changelog_contents}")
  set(package_version "${CMAKE_MATCH_1}${ADBSCAN_PACKAGE_VERSION_SUFFIX}")
  if(package_version STREQUAL "")
    message(FATAL_ERROR "Package version not found in ${changelog_file}")
  endif()

  install(FILES "${changelog_file}"
    DESTINATION "share/doc/${ROS_DEBIAN_PACKAGE_NAME}"
    RENAME "changelog.Debian"
  )

  string(REPLACE ";" ", " package_dependencies "${ROS_DEBIAN_DEPENDS}")
  string(REPLACE ";" ", " package_recommends "${ROS_DEBIAN_RECOMMENDS}")

  set(CPACK_GENERATOR "DEB")
  set(CPACK_PACKAGE_NAME "${ROS_DEBIAN_PACKAGE_NAME}")
  set(CPACK_PACKAGE_VERSION "${package_version}")
  set(CPACK_PACKAGE_CONTACT "${ROS_DEBIAN_CONTACT}")
  set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${ROS_DEBIAN_DESCRIPTION}")
  set(CPACK_PACKAGING_INSTALL_PREFIX "/opt/ros/${ROS_DISTRO}")
  set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
  set(CPACK_DEBIAN_PACKAGE_DEPENDS "${package_dependencies}")
  set(CPACK_DEBIAN_PACKAGE_RECOMMENDS "${package_recommends}")
  set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

  include(CPack)
endfunction()
